version: 2.1
jobs:
  build:
    docker:
      - image: cimg/openjdk:11
    steps:
      - checkout
      - restore_cache:
          key: bare-jvm-{{ checksum "pom.xml" }}
      - run: mvn -Dmaven.test.skip=true package
      - save_cache:
         paths: ~/.m2
         key: bare-jvm-{{ checksum "pom.xml" }}
      - run: mvn test
      - run: bash <(curl -s https://codecov.io/bash)
      - store_test_results:
          path: target/surefire-reports