version: 2.1
orbs:
  maven: circleci/maven@1.0.3
  codecov: codecov/codecov@1.1.1

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
      - codecov/upload